services:
  postgres:
    image: postgres:16.1
    container_name: atomic-forge-postgres
    environment:
      POSTGRES_DB: atomic_forge_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - atomic-forge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Optional: Add pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: atomic-forge-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@atomic-forge.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - atomic-forge-network

volumes:
  postgres_data:

networks:
  atomic-forge-network:
    driver: bridge