name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: atomic_oxide_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install diesel CLI
      run: |
        cargo install diesel_cli --no-default-features --features postgres || true

    - name: Setup test database
      working-directory: ./atomic-oxide
      env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/atomic_oxide_test
        TEST_DATABASE_URL: postgres://postgres:password@localhost:5432/atomic_oxide_test
      run: |
        diesel migration run

    - name: Run tests
      working-directory: ./atomic-oxide
      env:
        TEST_DATABASE_URL: postgres://postgres:password@localhost:5432/atomic_oxide_test
      run: cargo test --verbose

    - name: Check formatting
      working-directory: ./atomic-oxide
      run: cargo fmt -- --check

    - name: Run clippy
      working-directory: ./atomic-oxide
      run: cargo clippy -- -D warnings